PROBABILISTIC_STRATEGIES = ["probabilistic", "gpt+probabilistic"]
PROBABILISTIC_RANKING_STRATEGIES = PROBABILISTIC_STRATEGIES + ["ranking"]
GPT_STRATEGIES = ["gpt", "gpt+probabilistic"]
GPT_ONLY_STRATEGIES = ["gpt"]
GPT_COMBINED_STRATEGIES = ["gpt+probabilistic"]

NON_RANDOM_STRATEGIES = PROBABILISTIC_RANKING_STRATEGIES + GPT_STRATEGIES
